# Generated by Django 5.0.6 on 2024-07-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Acessorio",
        ),
    ]
